// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXXj8UGoWB-ERPhD25H6ycSFVeIEI5ufQ',
    appId: '1:786953078927:web:de12433b8eb1bf683288fa',
    messagingSenderId: '786953078927',
    projectId: 'coco-home-698d0',
    authDomain: 'coco-home-698d0.firebaseapp.com',
    storageBucket: 'coco-home-698d0.firebasestorage.app',
    measurementId: 'G-FH6D54C0SB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg21ds-pW7qimjdpYs49FL1wQMMCfPldU',
    appId: '1:786953078927:android:7206f714a0d258813288fa',
    messagingSenderId: '786953078927',
    projectId: 'coco-home-698d0',
    storageBucket: 'coco-home-698d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgUb0rpFJGO6JV1krn0iVs4DABZ4eLViQ',
    appId: '1:786953078927:ios:025726900dc7d5513288fa',
    messagingSenderId: '786953078927',
    projectId: 'coco-home-698d0',
    storageBucket: 'coco-home-698d0.firebasestorage.app',
    iosBundleId: 'solutions.bluestem.cocoHome',
  );

}